---
ignore:
  - idea./
#  - tests/
  - setup.py

rule_settings:
  enable:
    - default
    - gpsg-import
    - gpsg-naming-pep8
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.7'

rules: []

metrics:
  quality_threshold: 75.0

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

proxy:
  no_ssl_verify: false
