[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "daily-tracker"
version = "0.0.0"
description = "An application for keeping track of tasks throughout the day."
authors = ["Bilbottom"]
readme = "README.md"
repository = "https://github.com/Bilbottom/daily-tracker"
packages = [
    {include = "daily_tracker"},
    {include = "core", from = "daily_tracker"},
    {include = "integrations", from = "daily_tracker"},
]

[tool.poetry.scripts]
daily-tracker = "daily_tracker.__main__:main"

[tool.poetry.dependencies]
python = "^3.11"
Pillow = ">=9.4.0"
python-dotenv = ">=0.21.1"
requests = ">=2.28.2"
slack-sdk = ">=3.20.0"
pyyaml = ">=6.0"

pywin32 = [
    {platform = "win32", version = "305"}
]
appscript = [
    {platform = "darwin", version = "1.2.2"}
]


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
coverage-badge = "^1"
pre-commit = "^3"
pylint = "^2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"


[tool.pytest.ini_options]
addopts = "--cov=daily_tracker --cov-report term-missing"
testpaths = ["tests"]


[tool.black]
target_version = ["py311"]
line-length = 80


[tool.isort]
profile = "black"
line_length = 80
known_local_folder = "daily_tracker,core,integrations,tracker_utils"


[tool.pylint.format]
max-line-length = 80

[tool.pylint.MASTER]
ignore-paths = "^tests/.*$"
