[build-system]
requires = ["setuptools >= 42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "daily-tracker"
description = "An application for keeping track of tasks throughout the day."
version = "0.0.0"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["readme", "dependencies", "optional-dependencies"]

[project.urls]
repository = "https://github.com/Bilbottom/daily-tracker"

[project.scripts]
daily-tracker = "daily_tracker.__main__:main"


[tool.setuptools]
platforms = ["win32"]


[tool.setuptools.dynamic]
readme = { file = "README.md" }
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}


[tool.pytest.ini_options]
addopts = "--cov=daily_tracker --cov-report term-missing"
testpaths = [
    "tests",
]


[tool.isort]
profile = "black"


[tool.black]
line-length = 80
target_version = ['py311']
