---
# TODO: Consider splitting by system like the classes have been instead of using
#       the category property

tracker:
  # Options to configure how the pop-up box functions
  options:
    interval:
      value: 15
      type: integer
      category: tracker
      description: >
        The time, in minutes, between each of the pop-up boxes.

        Positive whole numbers only.

    run-on-startup:
      value: Yes
      type: boolean
      allowed-values: [Yes, No]
      category: tracker
      description: >
        Whether or not the tracker should start running when the application is
        initialised.

        Values of "Yes" or "No" only.

    show-last-n-weeks:
      value: 2
      type: integer
      category: tracker
      description: >
        Whether or not the tracker should start running when the application is
        initialised.

        Positive whole numbers only.

    use-calendar-appointments:
      value: No
      type: boolean
      allowed-values: [Yes, No]
      category: calendar
      description: >
        Whether or not the tracker should auto-fill with meeting details from
        the linked calendar.

        Values of "Yes" or "No" only.

    appointment-category-exclusions:
      value:
        - Planned Work
      type: list
      category: calendar
      description: >
        The categories to exclude when filling the form with details from the
        linked calendar.

        Values must be a list of strings. The available values should be synced
        from the linked calendar.

    linked-calendar:
      value: none
      type: string
      allowed-values: [none, outlook, gmail]
      category: calendar
      description: >
        Whether or not the tracker should auto-fill with meeting details from
        the linked calendar.

        Values of "Yes" or "No" only.

    jira-type:
      value: cloud
      type: string
      allowed-values: [cloud, server]
      category: jira
      description: >
        The type of Jira platform to connect to.

        Values of "cloud" or "server" only.

    use-jira-sprint:
      value: No
      type: boolean
      allowed-values: [Yes, No]
      category: jira
      description: >
        Whether or not the tracker should auto-fill with task details from the
        linked Jira filter.

        Values of "Yes" or "No" only.

    post-to-jira:
      value: No
      type: boolean
      allowed-values: [Yes, No]
      category: jira
      description: >
        Whether or not the tracker should update the linked Jira ticket in Jira
        with a worklog.

        Values of "Yes" or "No" only.

    post-to-slack:
      value: No
      type: boolean
      allowed-values: [Yes, No]
      category: slack
      description: >
        Whether or not the tracker should post a message with the entered pop-up
        values to a Slack channel.

        Values of "Yes" or "No" only.

    save-csv-copy:
      value: No
      type: boolean
      allowed-values: [Yes, No]
      category: tracker
      description: >
        Whether or not the tracker should save a copy of the full history to a
        CSV file. If "Yes" is specified, then the `csv-filepath` property must
        be given an absolute filepath of the *directory* to save the file to.

        Values of "Yes" or "No" only.

    csv-filepath:
      value: null
      type: string
      category: tracker
      description: >
        The absolute filepath of the *directory* to save a CSV copy of the full
        history to. This will not be used unless the `save-csv-copy` property is
        set to "Yes".

    appointment-exceptions:
      value:
        - name: Daily Jira Call
          task: Catch Ups
          detail: Daily Jira Call
        - name: Jira Scrum
          task: Catch Ups
          detail: Jira Scrum
        - name: Jira Scrum / Team Meeting
          task: Catch Ups
          detail: Jira Scrum
        - name: Planning
          task: Catch Ups
          detail: Planning
        - name: Nik & Bill Catch Up
          task: Catch Ups
          detail: Nik & Bill
        - name: Nik & Bill Developmental Catch Up
          task: Catch Ups
          detail: Nik & Bill
        - name: 1-2-1 Bill & Juliana
          task: Catch Ups
          detail: Juliana & Bill
        - name: Manage Jira Tickets
          task: Housekeeping
          detail: Manage Jira Tickets
        - name: Personal Development on Alteryx
          task: Personal Development
          detail: Alteryx
        - name: Personal Development on Tableau
          task: Personal Development
          detail: Tableau
      type: list
      category: calendar
      description: >
        Exceptions to use when filling the form with details from the
        linked calendar.

        This is to extend the functionality of the linked calendar to add other
        task values that just "Meeting".

        Values must be a list of the meeting names that are the exceptions, with
        a 2-tuple replacement (the new task and detail, respectively).
