name: Unit Tests
run-name: Unit tests triggered by ${{ github.actor }}

on:
  push:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  unit-tests-and-formatting:
    runs-on: windows-latest
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 🔨 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: 🔮 Log in to Sourcery
        shell: bash
        env:
          SOURCERY_TOKEN: ${{ secrets.SOURCERY_TOKEN }}
        run: |
          sourcery login --token "$SOURCERY_TOKEN"

      - name: ✅ Test with pytest and sourcery
        run: |
          pytest tests
          sourcery review src
